apiVersion: v1
kind: Service
metadata:
  name: service-events
spec:
  selector:
    app: service-events
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-events
spec:
  selector:
    matchLabels:
      app: service-events
  replicas: 1
  template:
    metadata:
      labels:
        app: service-events
    spec:
      containers:
        - name: server
          image: skor39/service-events
          ports:
            - name: http
              containerPort: 8083

---
