apiVersion: v1
kind: Service
metadata:
  name: service-tickets
spec:
  selector:
    app: service-tickets
  type: NodePort
  ports:
    - name: http
      port: 8084
      nodePort: 31003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-tickets
spec:
  selector:
    matchLabels:
      app: service-tickets
  replicas: 1
  template:
    metadata:
      labels:
        app: service-tickets
    spec:
      containers:
        - name: server
          image: skor39/service-tickets
          ports:
            - name: http
              containerPort: 8084

---
